create table links (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  link text check (char_length(link) > 3),
  is_complete boolean default false,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table links enable row level security;
create policy "Individuals can create links." on links for
    insert with check (auth.uid() = user_id);
create policy "Individuals can view their own links. " on links for
    select using (auth.uid() = user_id);
create policy "Individuals can update their own links." on links for
    update using (auth.uid() = user_id);
create policy "Individuals can delete their own links." on links for
    delete using (auth.uid() = user_id);